# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 48246e421b6962e1473682ec2b1b8f7ecb0dc4f115e56503a18446fb22cdb363e1e0ef6ef4e82d9c46a20e2a153c4b71b19fe05376bdac77b15882df8e7a9a8b

test:
  secret_key_base: 420e05eb9104879de077c9e91ca3957be4f29295a0ff17ba10fb0755744ad7d6a9e1b81a67c3b2ac8f830aaf8bd041b4f435f72d7820fd540e3f89fba72e5537

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
